<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Josour.Egress</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Josour.Core/Josour.Core.csproj" />
    <ProjectReference Include="../Josour.Tunnel/Josour.Tunnel.csproj" />
  </ItemGroup>

</Project>
