<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>RouteBridge.Egress</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../RouteBridge.Core/RouteBridge.Core.csproj" />
    <ProjectReference Include="../RouteBridge.Tunnel/RouteBridge.Tunnel.csproj" />
  </ItemGroup>

</Project>
